<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>EcommerceWebApi</RootNamespace>
		<AssemblyName>EcommerceWebApi</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="JsonFlatFileDataStore" Version="2.4.2" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.11" />
		<PackageReference Include="Otp.NET" Version="1.4.0" />
		<PackageReference Include="Serilog.Extensions.Logging.File" Version="3.0.0" />
		<PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Logs\" />
	</ItemGroup>

</Project>
