apiVersion: v1
kind: Service
metadata:
  name: ecommerce-mcontmono-service
  namespace: ecommerce-mcontmono
  labels:
    app: ecommerce-mcontmono
    managed-by: kubectl
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: ecommerce-mcontmono
